import numpy as np
# 1-D Array/ Vector
a = np.array([1, 2, 3])
print(a)
print(type(a))
# 2-D Array/ Matrix
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
# 3-D Array
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)
# d-type
d = np.array([1, 2, 3], dtype = float)
print(d)
d = np.array([1, 2, 0], dtype = bool)
print(d)
d = np.array([1, 2, 3], dtype = complex)
print(d)
e = np.arange(1,11)
print(e)
e = np.arange(1,11).reshape(5, 2)
print(e)
e = np.arange(1,11).reshape(2, 5)
print(e)
f = np.ones(10).reshape(2,5)
print(f)
f = np.zeros(10).reshape(2,5)
print(f)
g = np.random.random((3,4))
print(g)
h = np.linspace(-10, 10, 10).reshape(2,5)
print(h)
i = np.identity(3,dtype=int)
print(i)
print(i.ndim)
j = np.arange(10)
print(j.ndim)
print(j.shape)
print(j.size)
j = np.arange(10).reshape(2,5)
print(j.ndim)
print(j.shape)
print(j.size)
j = np.arange(18, dtype=np.int32).reshape(2,3,3)
print(j.ndim)
print(j.shape)
print(j.size)
print(j.itemsize)
j = np.arange(18, dtype=np.int64).reshape(2,3,3)
print(j.ndim)
print(j.shape)
print(j.size)
print(j.itemsize)
print(a.dtype)
print(b.dtype)
print(c.dtype)
print(d.dtype)
a.astype(np.int32)
print(a.size)
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1 + a2)
print(a2 - a1)
print(a1 * a2)
print(a1 / a2)
print(a1 ** a2)
print(a2 > 15)
print(a1 > a2)
print(a2 == 15)
a1 = np.random.random((3,3))
a1 = np.round(a1 * 100)
print(a1)
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))
# 0 -> col and 1 -> row
print(np.sum(a1, axis = 0))
print(np.sum(a1, axis = 1))
print(np.max(a1, axis = 0))
print(np.max(a1, axis = 1))
print(np.min(a1, axis = 0))
print(np.min(a1, axis = 1))
print(np.prod(a1, axis = 0))
print(np.prod(a1, axis = 1))
# mean/median/standard deviation/variance
print(np.mean(a1))
print(np.mean(a1, axis = 0))
print(np.mean(a1, axis = 1))
print(np.median(a1))
print(np.median(a1, axis = 0))
print(np.median(a1, axis = 1))
print(np.std(a1))
print(np.std(a1, axis = 0))
print(np.std(a1, axis = 1))
print(np.var(a1))
print(np.var(a1, axis = 0))
print(np.var(a1, axis = 1))
# Matrix Multiplication
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
print(np.dot(a2, a3))
print(a2 @ a3)
print(np.matmul(a2, a3))
# Trigonometric Functions
print(np.sin(a1))
print(np.cos(a1))
print(np.tan(a1))
print(np.sinh(a1))
print(np.cosh(a1))
print(np.tanh(a1))
# Logerathemic and Exponential Functions
print(np.log(a1))
print(np.exp(a1))
# round/floor/ceil
print(np.round(np.random.random((3,3))*100))
print(np.floor(np.random.random((3,3))*100))
print(np.ceil(np.random.random((3,3))*100))
# Iterating through an array
for i in np.nditer(np.arange(256).reshape(4,4,4,4)):
    print(i)
# Transpose/Ravel(Convert to 1-D Array) of a Matrix
print(a3)
print(a3.T)
print(np.transpose(a3))
print(a3.ravel())
# Stacking and Splitting
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
print(a4)
print(a5)
print(np.hstack((a4,a5)))
print(np.vstack((a4,a5)))
print(np.hsplit(a4,4))
print(np.vsplit(a5,3))
# Missing Values
k = np.array([1, 2, 3, 4, np.nan, 6])
print(k)
print(np.isnan(k))
print(~np.isnan(k))
print(k[~np.isnan(k)])